# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  git_url = "git@github.com:givtnl/givt.apps.codesigning.git"
  lane :certificates do
    match(type: "appstore", app_identifier: "net.givtapp.flutter.alpha", git_url: git_url)
  end
end
