name: Build iOS and upload to TestFlight
on: 
  push: 
    branches: [ pre-main ]
jobs:
  build-ios: 
    name: Build Flutter iOS
    runs-on: macos-latest
    defaults: 
      run:
        working-directory: ios
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.118.0
        with: 
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install Fastlane
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: ios certificates
